In [ ]:
!pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl


     |████████████████████████████████| 592.3MB 1.1MB/s 
ERROR: torchvision 0.8.1+cu101 has requirement torch==1.7.0, but you'll have torch 0.3.0.post4 which is incompatible.
ERROR: fastai 1.0.61 has requirement torch>=1.0.0, but you'll have torch 0.3.0.post4 which is incompatible.
  Found existing installation: torch 1.7.0+cu101
    Uninstalling torch-1.7.0+cu101:
      Successfully uninstalled torch-1.7.0+cu101


In [2]:
import torch
import numpy as np

In [3]:
#1D array(vector)
t=np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t :', t.ndim) #dimension
print('Shape of t :', t.shape)

Rank of t : 1
Shape of t : (7,)


In [5]:
print(t[1:4])

[1. 2. 3.]


In [6]:
#2D array
t=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [7]:
print('Rank of t :', t.ndim) #dimension
print('Shape of t :', t.shape) # row,col

Rank of t : 2
Shape of t : (4, 3)


In [8]:
#1D array with PyTorch
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.]) #float type tensor
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [11]:
print(t.dim())
print(t.shape) #shape
print(t.size()) #shape
print(t[0],t[1],t[2])
print(t[2:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(2.)
tensor([2., 3., 4., 5., 6.])


In [12]:
#2D array with pytorch
t=torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
print(t.dim()) #차원
print(t.size()) 
print(t[:,1]) #모든 행의 두번째 열
print(t[:,1].size())

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [9]:
#Same Shape
m1 = torch.FloatTensor([2,2]) #Vector
m2 = torch.FloatTensor([3,4])
print(m1+m2)

tensor([5., 6.])


In [10]:
# diff shape - 자동으로 boradcasting!!
m3=torch.FloatTensor([1]) # Scalar
print(m1+m3) #1->[[1,1]] #broadcasting

tensor([3., 3.])


In [11]:
m1=torch.FloatTensor([1,2]) #1X2 -> [1,2],[1,2]
m2=torch.FloatTensor([[3],[4]]) # 2 X 1 ->[3,3],[4,4]
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [12]:
## 행렬 곱 - 딥러닝에서 중요*
m1=torch.FloatTensor([[1,2],[3,4]]) # 2 X 2
m2 = torch.FloatTensor([[1],[2]]) # 2 X 1
print(m1.shape)
print(m2.shape)

torch.Size([2, 2])
torch.Size([2, 1])


In [14]:
print(m1.matmul(m2))
print(m1.matmul(m2).shape)

tensor([[ 5.],
        [11.]])
torch.Size([2, 1])


In [17]:
print(m1*m2)
print(m1.mul(m2))
#element 끼리 곱

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [18]:
t=torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [19]:
t=torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.mean())
print(t.mean(dim=0)) #dim 0 에 대해서 [[ , ]]의 형태로
print(t.mean(dim=1)) #dim 1에 대해서 [[],[]]의 형태로


tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [22]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


In [23]:
print(t.max())

tensor(4.)


In [25]:
print(t.max(dim=0))
print(t.max(dim=1))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [29]:
  t=np.array([[[0,1,2],[3,4,5]],
             [[6,7,8],[9,10,11]]])
  ft=torch.FloatTensor(t)
  print(ft.size()) # 2X3 행렬이 두개

torch.Size([2, 2, 3])


In [32]:
print(ft.dim()) #3차원
print(ft.size())

3
torch.Size([2, 2, 3])


In [33]:
print(ft.view([-1,3])) # 2D ? X3 matrix로 변환 - 값들을 형태에 맞게 재배열
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [35]:
print(ft.view(-1,1,3)) # 3차원 _X1X3 = 전체갯수가 되도록
print(ft.view(-1,1,3).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [38]:
#squeeze
ft=torch.FloatTensor([[0],[1],[2]])
print(ft.shape)

torch.Size([3, 1])


In [40]:
print(ft.squeeze()) #1인 dim 제거 즉, 3X1 -> 3
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [44]:
print(ft.squeeze(dim=0)) #첫번째 dim 3
print(ft.squeeze(dim=1)) #두번째 dim 1

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])


In [45]:
## Unsqueeze
ft=torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [52]:
print(ft.unsqueeze(0)) # 지정 dim을 1로 만듬.
print(ft.unsqueeze(0).shape) #

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [55]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [57]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [58]:
lt=torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [59]:
#Type Casting
print(lt.float())

tensor([1., 2., 3., 4.])


In [60]:
#boolean 저장 - ByteTensor
bt=torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [61]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [62]:
bt=(lt==3)
print(bt) #bt - byteTensor

tensor([False, False,  True, False])


In [63]:
###Concatenate
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

In [66]:
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=0).shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])


In [67]:
print(torch.cat([x,y],dim=1))
print(torch.cat([x,y],dim=1).shape)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
torch.Size([2, 4])


In [72]:
######Stacking
x=torch.FloatTensor([1,4]) 
y=torch.FloatTensor([2,5])
z=torch.FloatTensor([3,6])
print(x.shape , x.dim())

torch.Size([2]) 1


In [75]:
print(torch.stack([x,y,z]))  #dim=0
print(torch.stack([x,y,z]).size()) 

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


In [76]:
print(torch.stack([x,y,z],dim=1))
print(torch.stack([x,y,z]).size()) 

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([3, 2])


In [78]:
x=torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [79]:
print(torch.ones_like(x)) # x와 같은 shape 1로 가득찬.
print(torch.zeros_like(x))
#같은 device에..?

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [81]:
# inplace operation : _
x=torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [82]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
