In [1]:
import torch

In [2]:
torch.empty(5,3)

tensor([[5.0777e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

무작위로 size 5x3의 초기화되지 않은 행렬


In [5]:
x=torch.rand(5,3)
print(x)

tensor([[0.4681, 0.7029, 0.2717],
        [0.1149, 0.1535, 0.8796],
        [0.0315, 0.8342, 0.5973],
        [0.6465, 0.9425, 0.9967],
        [0.3017, 0.5285, 0.8467]])


무작위로 size 5x3의 초기화된 행렬

In [8]:
x=torch.zeros(5,3,dtype=torch.long) #0으로 채워진 행렬

In [9]:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x=x.new_ones(5,3,dtype=torch.int)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [12]:
x=torch.randn_like(x,dtype=torch.float) # norm =0, var=1 사이 어떤 값들
print(x)

tensor([[-0.7340,  2.4129, -0.2378],
        [-1.0568, -0.0249, -1.9961],
        [-0.1908, -0.8446,  1.1856],
        [ 0.1280,  2.5925,  0.7640],
        [-0.8846,  0.6993, -0.7188]])


In [13]:
print(x.size()) 

torch.Size([5, 3])


행렬의 크기

In [14]:
output=torch.add(x,x)
print(output)

tensor([[-1.4680,  4.8258, -0.4756],
        [-2.1135, -0.0498, -3.9923],
        [-0.3816, -1.6893,  2.3711],
        [ 0.2560,  5.1851,  1.5280],
        [-1.7693,  1.3986, -1.4375]])


In [15]:
print(output[:,1]) #numpy처럼 행, 열 추출가능

tensor([ 4.8258, -0.0498, -1.6893,  5.1851,  1.3986])


In [19]:
x=torch.randn(4,4)
y=x.view(16) #1 *16 으로 변경
z=x.view(-1,8) #8에 맞추어 2 * 8로 변경
print(y.size())
print(z.size())
print(x)
print(y)
print(z)

torch.Size([16])
torch.Size([2, 8])
tensor([[ 0.3430,  0.3180,  0.3146, -0.7319],
        [-2.2117,  0.4268,  0.2026, -0.1108],
        [ 1.2322,  0.7577, -2.1619, -1.2178],
        [-0.3706,  0.3610, -1.5295,  0.6198]])
tensor([ 0.3430,  0.3180,  0.3146, -0.7319, -2.2117,  0.4268,  0.2026, -0.1108,
         1.2322,  0.7577, -2.1619, -1.2178, -0.3706,  0.3610, -1.5295,  0.6198])
tensor([[ 0.3430,  0.3180,  0.3146, -0.7319, -2.2117,  0.4268,  0.2026, -0.1108],
        [ 1.2322,  0.7577, -2.1619, -1.2178, -0.3706,  0.3610, -1.5295,  0.6198]])


RuntimeError: ignored

torch.view : tensor의 size와 shape을 변경

In [22]:
x=torch.rand(1)
print(x.item())

0.3570863604545593


.item() : tensor에 하나의 값만 존재할 경우

#Tensor <-> Numpy


In [23]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


# PYTORCH

*각 function의 사용법은 documentation [링크 텍스트](https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html) 참조     
pyTorch에서 제공되는 nn 패키지는 layer들과 거의 동일한 Module의 집합


In [37]:
import torch

# N 배치크기, D_in 입력차원
# D_out 출력차원, H는 은닉층의 차원
N,D_in,H,D_out=64,1000,100,10

x=torch.randn(N,D_in) 
y=torch.randn(N,D_out) 

# nn 패키지 활용 - 모델을 순차저 계층 (sequence of layers)
# nn.Sequential : 다른 module을 포함하는 module이며, module을 순차적 적용하여 출력 생성.
model = torch.nn.Sequential(
    torch.nn.Linear(D_in,H),
    torch.nn.ReLU(),
    torch.nn.Linear(H,D_out),
)

In [43]:
##nn package 에는 손실함수( loss function) 에 대한 정의도 포함.
#여기서는 Mean Squard Error (MSE ) 사용
loss_fn=torch.nn.MSELoss(reduction='sum')

learning_rate=1e-4


In [42]:
epoch=1000
for t in range(epoch):
  # 순전파 : model에 input x 를 전달하여 output 계산
  y_pred=model(x)

  #손실값을 갖는 Tensor return
  loss = loss_fn(y_pred,y)
  if(t%100 ==99 ):
    print(t,loss.item())

99 670.0565795898438
199 670.0565795898438
299 670.0565795898438
399 670.0565795898438
499 670.0565795898438
599 670.0565795898438
699 670.0565795898438
799 670.0565795898438
899 670.0565795898438
999 670.0565795898438


In [44]:
#Backpropogation 이전 변화도를 0으로
model.zero_grad()

#Model의 학습가능한 모든 매개변수에 대해 손실의 변화도 계산
loss.backward()

#Gradient descent 활용하여 가중치 갱신
with torch.no_grad():
  for params in model.parameters():
    params -= learning_rate*params.grad


# Optimizer을 활용하여 가중치 갱신

In [45]:
import torch

# N 배치크기, D_in 입력차원
# D_out 출력차원, H는 은닉층의 차원
N,D_in,H,D_out=64,1000,100,10

x=torch.randn(N,D_in) 
y=torch.randn(N,D_out) 

# nn 패키지 활용 - 모델을 순차저 계층 (sequence of layers)
# nn.Sequential : 다른 module을 포함하는 module이며, module을 순차적 적용하여 출력 생성.
model = torch.nn.Sequential(
    torch.nn.Linear(D_in,H),
    torch.nn.ReLU(),
    torch.nn.Linear(H,D_out),
)

In [46]:

loss_fn=torch.nn.MSELoss(reduction='sum')

In [49]:
#optim package는 다양한 최적화 알고리즘 포함.
learning_rate = 1e-9
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [50]:
for t in range(500):
  y_pred = model(x)

  loss=loss_fn(y_pred,y)
  if(t%100==99):
    print(t,loss.item())

  # Backpropogation 전 단계에 Optimizer 객체 활용하여 갱신할 parameter에 대한 모든 변화도를 0으로
  # 왜? .backward()호출 시 변화도가 buffer에 누적되기 때문.

  optimizer.zero_grad()

  # backpropogation - loss의 변화도 계산
  loss.backward()
  
  # 매개변수 갱신
  optimizer.step()

99 7.623638680342992e-07
199 6.800443088650354e-07
299 6.12891881246469e-07
399 5.575712407335232e-07
499 5.136965341989708e-07


# pyTorch 사용자 정의 : nn.Module


기존 모듈(sequence)보다 더 복잡한 모델 구성이 필요한 경우   
nn.Module의 서브 클래스로 새 모듈 정의한 후, input을 받아 출력 Tensor을 만든다

In [59]:
class TwoLayerNet(torch.nn.Module):
  def __init__(self,D_in,H,D_out):
    #nn.module을 상속받아 생성자에서 linear1, linear2 두 멤버변수 생성
    super(TwoLayerNet,self).__init__()
    self.linear1 = torch.nn.Linear(D_in,H) 
    self.linear2 = torch.nn.Linear(H,D_out)

    def forward(self,x):
      # 입력데이터의 tensor x를 받고 출력데이터의 tensor을 반환
      h_relu=self.linear1(x)
      y_pred=self.linear2(h_relu)

      return y_pred

In [60]:
N, D_in, H, D_out = 64,1000,100,10

x= torch.randn(N,D_in)
y= torch.randn(N,D_out)

In [61]:
model = TwoLayerNet(D_in,H,D_out)

criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

for t in range(500):
    y_pred = model(x)

    loss=criterion(y_pred,y)
    if(t%100==99):
      print(t,loss.item())

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

NotImplementedError: ignored